### ISSUE TITLE
Do not use class when not necessary

### ISSUE THREAD

**Issue by stephen-hqxu** [stephen-hqxu/superterrainplus#52]
### Problem

It is redundant to use a class for something like this:

```cpp

class Foo {
private:
	Precondition precond;
	Intermediate interm;
	Bar result;
public:
	//store precondition
	Foo(...) {
		//do something
		// ...
		//store
		this->precond = precondition_data;
	}
	//store intermediate states
	void addData(const Intermediate& middle) {
		this->interm = middle;
	}
	void finalise() {
		//use precondition and intermediate data to do stuff
		// ...
		//store
		this->result = result_data;
	}
	const Bar& get() const noexcept {
		return this->bar;
	}
};

```

Which can be generally simplified to:

```cpp

namespace Foo {
	Bar doStuff(const Precondition& precond, const Intermediate& interm) {
		//do something with precondition and intermediate data
		// ...
		//finish
		return result;
	}
}

```

### Task

Remove class design and turn it into non-OOP if the only member function in the class is a getter function to the result, for the following files:

- [x] [STPINIWriter](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain+/ModuleInterface/SuperAlgorithm+/Parser/INI/STPINIWriter.h)
- [x] [STPINIReader](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperAlgorithm%2B/Parser/INI/STPINIReader.h)
- [x] [STPTextureDefinitionLanguage](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperAlgorithm%2B/Parser/STPTextureDefinitionLanguage.h)
- [x] [STPSimplexNoise](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperAlgorithm%2B/Device/STPSimplexNoise.cuh)
- [x] [STPSingleHistogramWrapper](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain+/ModuleInterface/SuperAlgorithm+/Device/STPSingleHistogramWrapper.cuh)
- [x] [STPTextureSplatRuleWrapper](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperAlgorithm%2B/Device/STPTextureSplatRuleWrapper.cuh)
- [x] [STPPermutationGenerator](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperAlgorithm%2B/STPPermutationGenerator.h)
- [x] [STPErosionBrushGenerator](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/CoreInterface/SuperTerrain%2B/World/Chunk/STPErosionBrushGenerator.h)
- [x] [STPBindlessBuffer](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperRealism%2B/Object/STPBindlessBuffer.h)
- [x] [STPBindlessTexture](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperRealism%2B/Object/STPBindlessTexture.h)
- [x] [STPShaderManager](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperRealism%2B/Object/STPShaderManager.h)
- [x] [STPProgramManager](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperRealism%2B/Object/STPProgramManager.h)
- [x] [STPPipelineManager](https://github.com/stephen-hqxu/superterrainplus/blob/v0.15.1/SuperTerrain%2B/ModuleInterface/SuperRealism%2B/Object/STPPipelineManager.h)

**Comment by stephen-hqxu** [comment]
Class refactor and improvement for source code in `SuperAlgorithm+Device` are done.

**Comment by stephen-hqxu** [comment]
The majority of tasks are done, only left with a few parser libraries, for which I may do it together with #51.
